# from sys_params import *
# from scipy.interpolate import PchipInterpolator

# # Given constants
# omega_c = 136.5483127843927
# E_reorg = 30.344069507642818

# hbar_beta_vib = 0.025
# # Define the spectral density function J_vib(w)
# def J_vib(w):
#     k_vib_2 = E_reorg / (2 * omega_c**3)
#     return (k_vib_2 * (np.abs(w))**3) * np.exp(- (np.abs(w) / omega_c)**2)

# # Define the Phi(t) function
# def Phi(t):
#     integrand = lambda w: J_vib(w) * (np.cos(w * t) * (1 / np.tanh((hbar_beta_vib * np.abs(w)) / 2)) - 1j * np.sin(w * t)) / w**2
#     result = quad_vec(integrand, 1.0e-4, 500)
#     return result[0] 

# # def Phi(t):
# #     integrand = lambda w: J_vib(w) * (np.cos(w * t) * (1 / np.tanh((hbar_beta_vib * np.abs(w)) / 2)) - 1j * np.sin(w * t)) / w**2
# #     omega = np.linspace(1.0e-4, 500, 10000)
# #     inte = [integrand(w) for w in omega]
# #     result = simpson(inte, omega)
# #     return result


# # Parameters
# t_max = 1.0  # Maximum time
# n_points = 10000  # Number of points in time domain

# # Time array
# t = np.linspace(0, t_max, n_points)
# dt = t[1] - t[0]  # Time step

# # Frequency array generated by FFT
# omega_fft = fftfreq(n_points, d=dt) * 2 * np.pi
# omega_fft_shifted = fftshift(omega_fft)

# # Custom frequency array
# omega_custom = np.array([    0.        , -2679.45494719, -2769.03169848, -5448.48664566,
#         2679.45494719,     0.        ,   -89.57675129, -2769.03169848,
#         2769.03169848,    89.57675129,     0.        , -2679.45494719,
#         5448.48664566,  2769.03169848,  2679.45494719,     0.        ])

# # Define the exponential decay function
# f_t = 2006 * (np.exp(2 * Phi(t)) - 1)

# # Fourier Transform using DFT (FFT)
# F_dft = ifft(f_t) #* dt
# F_dft_shifted = ifftshift(F_dft)

# # Interpolate FFT result onto custom frequency array
# pchip_interpolator = PchipInterpolator(omega_fft_shifted, F_dft_shifted)
# F_dft_custom = pchip_interpolator(omega_custom)

# # # Fourier Transform using Simpson's integration with the same custom frequency array
# # F_simps_custom = np.array([simpson(f_t * np.exp(1j * w * t), t) for w in omega_custom])

# # # Define the trapezoidal rule for integration
# # def trapezoidal_rule(f, t):
# #     return np.trapz(f, t)

# # F_trapz_custom = np.array([trapezoidal_rule(f_t * np.exp(1j * w * t), t) for w in omega_custom])

# # Plot the results
# plt.figure(figsize=(12, 6))
# plt.scatter(omega_custom, np.abs(F_dft_custom), label="FFT with custom freq array", color='blue')
# # plt.scatter(omega_custom, np.abs(F_simps_custom), label="Simpson's Integration", color='red')
# # plt.scatter(omega_custom, np.abs(F_trapz_custom), label="Trapz Integration", color='black')
# plt.xlabel("Frequency (rad/s)")
# plt.ylabel("Amplitude")
# plt.title("Comparison of Fourier Transform Methods")
# plt.legend()
# plt.grid(True)
# plt.show()

# # print(np.round(F_dft_custom, 6))
# # print(F_simps_custom)
# # print(F_trapz_custom)

# # # Fourier Transform using quad for each frequency in omega_custom
# # F_quad_custom = np.array([quad(lambda t: integrand(t, w), 0, t_max)[0] for w in omega_custom])











# '''Extrapolation is dangerous'''

# '''n_points = 1000'''
# # [3.28178408-3.06899673j 0.17533218+0.04979311j 0.17533218+0.04138918j
# #  0.17533209-0.18384844j 0.17533217-0.03301341j 3.28178408-3.06899673j
# #  5.30638263+0.2620117j  0.17533218+0.04138918j 0.17533217-0.02492753j
# #  0.72189371-2.54420472j 3.28178408-3.06899673j 0.17533218+0.04979311j
# #  0.17533217+0.22103102j 0.17533217-0.02492753j 0.17533217-0.03301341j
# #  3.28178408-3.06899673j]

# '''n_points = 10000'''
# # [3.12398372-3.07161295j 0.01753164+0.13483293j 0.01753164+0.13026186j
# #  0.01753164+0.0638841j  0.01753164-0.12590966j 3.12398372-3.07161295j
# #  5.1485821 +0.26198859j 0.01753164+0.13026186j 0.01753164-0.12190579j
# #  0.56409317-2.54941617j 3.12398372-3.07161295j 0.01753164+0.13483293j
# #  0.01753164-0.06169277j 0.01753164-0.12190579j 0.01753164-0.12590966j
# #  3.12398372-3.07161295j]

# '''n_points = 1000'''
# # [ 3.10645210e+00-3.07164554j -1.63786738e-07+0.26181592j -2.42316187e-06+0.2996552j  
# #  -5.56500001e-08-0.384614j -5.75638047e-03-0.37014348j  3.10645210e+00-3.07164554j
# #   5.13105132e+00+0.26198377j -2.42316187e-06+0.2996552j -2.83245700e-02-0.4952095j   
# #   5.46562397e-01-2.54948513j  3.10645210e+00-3.07164554j -1.63786738e-07+0.26181592j
# #   1.06129450e-05+0.47998465j -2.83245700e-02-0.4952095j -5.75638047e-03-0.37014348j  
# #   3.10645210e+00-3.07164554j]

# '''n_points = 1000'''
# # [ 3.10645210e+00-3.06899673j -2.23033321e-09+0.04979307j -5.72491684e-09+0.04138918j 
# #  -4.82594052e-08-0.35541826j -2.11785513e-09-0.03301336j  3.10645210e+00-3.06899673j
# #   5.13105132e+00+0.26200762j -5.72491684e-09+0.04138918j -5.62842991e-09-0.02492752j  
# #   5.46562396e-01-2.54420062j  3.10645210e+00-3.06899673j -2.23033321e-09+0.04979307j
# #   1.06201601e-05+0.45713755j -5.62842991e-09-0.02492752j -2.11785513e-09-0.03301336j  
# #   3.10645210e+00-3.06899673j]


# '''Using simpson for Phi'''

# '''n_points = 10000'''
# # [4.424907-2.894321j 0.612749+0.148258j 0.612751+0.118676j
# #  0.612932-0.726012j 0.612782-0.148257j 4.424907-2.894321j
# #  4.374957+0.486539j 0.612751+0.118676j 0.612777-0.118675j
# #  4.346923-0.488721j 4.424907-2.894321j 0.612749+0.148258j
# #  0.61278 +0.725726j 0.612777-0.118675j 0.612782-0.148257j
# #  4.424907-2.894321j]

# # [ 3.81218887-2.89432068j -1.14655791+1.29955621j -1.17419606+0.84384645j
# #   0.1491179 -1.77884668j -1.15941402-1.29893164j  3.81218887-2.89432068j
# #   3.76223826+0.49594552j -1.17419606+0.84384645j -1.17965644-0.84320152j
# #   3.73420646-0.49812745j  3.81218887-2.89432068j -1.14655791+1.29955621j
# #   0.14788587+1.78079659j -1.17965644-0.84320152j -1.15941402-1.29893164j
# #   3.81218887-2.89432068j]

# # [3.81221077e+00-2.8943206j  5.32096473e-05+0.14825801j 5.53537169e-05+0.11867584j 
# #  1.49132614e-01-1.68533582j 8.61017598e-05-0.14825747j 3.81221077e+00-2.8943206j 
# #  3.76226119e+00+0.48653931j 5.53537169e-05+0.11867584j 8.11246873e-05-0.11867532j 
# #  3.73422743e+00-0.48872108j 3.81221077e+00-2.8943206j  5.32096473e-05+0.14825801j
# #  1.47924541e-01+1.68728594j 8.11246873e-05-0.11867532j 8.61017598e-05-0.14825747j 
# #  3.81221077e+00-2.8943206j ]



import numpy as np
import matplotlib.pyplot as plt
from scipy.fft import fft, fftfreq, rfft, fftshift, ifft, ifftshift
from scipy.linalg import expm, null_space


def Liouvillian(H, Ls, hbar = 1):
    d = len(H) # dimension of the system
    superH = -1j/hbar * ( np.kron(np.eye(d),H)-np.kron(H.T,np.eye(d)) ) # Hamiltonian part
    superL = sum([np.kron(L.conjugate(),L) 
                  - 1/2 * ( np.kron(np.eye(d),L.conjugate().T.dot(L)) +
                            np.kron(L.T.dot(L.conjugate()),np.eye(d)) 
                          ) for L in Ls])
    return superH + superL



Omega, Gamma = 1,0.1 # Rabi frequency and decay rate                       
sm = np.array([[0., 0.], [1., 0.]]) # emission operator           
sp = sm.conj().T # absorption operator
H = np.array([[0, Omega], [Omega, 0]])/2 # Hamiltonian
c_ops = [np.sqrt(Gamma)*sm] # collapse operators

L = Liouvillian(H,c_ops) # Liouvillian
rho_ss = np.reshape(null_space(L), (2,2) ) # steady state
rho_ss /= np.trace(rho_ss) # normalised steady state
dim = len(rho_ss) # system dimension

# ---> correlation function 
N = 2000 # samples
times = np.linspace(0.0, 500., N) # time interval              
corrs = np.zeros(N, dtype = complex) # correlation array
dt = times[1]-times[0] # time-step finite difference
P = expm(L * dt) # propagator
B_ss = sm@rho_ss # emission operator applied to steady state
vec_B_ss = np.reshape(B_ss,(dim**2,1)) # vector form of B_ss 

# calculate correlation function over the time interval
for kt,t in enumerate(times):
    corrs[kt] = np.trace(sp@np.reshape(vec_B_ss,(dim,dim))) # collect correlation
    vec_B_ss = P.dot(vec_B_ss) # propagate operator using semigroup composition rule
    
# ---> Obtain correlation spectrum using discrete fourier transform
spec = 2 * np.real(fft(corrs)) * dt # spectrum
wlist = 2 * np.pi*fftfreq(N, dt) # angular frequencies

spec = fftshift(spec)
wlist = fftshift(wlist)

plt.plot(wlist, spec)
plt.xlim(-2,2)
plt.show()